include: package:lints/recommended.yaml

linter:
  rules:
    unrelated_type_equality_checks: false
    implementation_imports: false

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
